name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues and this feature has not been requested
          required: true

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature or improvement you'd like
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      placeholder: This would help because...
    validations:
      required: false
